// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTCHrDbKvtJUGAMvgPTBhM2w7J6mpZpG8',
    appId: '1:892944225380:web:77e0b3af76998315b53b71',
    messagingSenderId: '892944225380',
    projectId: 'bitirmeprojesi-bd29f',
    authDomain: 'bitirmeprojesi-bd29f.firebaseapp.com',
    storageBucket: 'bitirmeprojesi-bd29f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy7z2yIXWOrFk-5j9whcaIM7W6TXLp3X0',
    appId: '1:892944225380:android:1f1255d189adfd9bb53b71',
    messagingSenderId: '892944225380',
    projectId: 'bitirmeprojesi-bd29f',
    storageBucket: 'bitirmeprojesi-bd29f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgPs89CAhb24_cnEABOKyLqIGlMxDptYY',
    appId: '1:892944225380:ios:c7fb6af60c68df68b53b71',
    messagingSenderId: '892944225380',
    projectId: 'bitirmeprojesi-bd29f',
    storageBucket: 'bitirmeprojesi-bd29f.appspot.com',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgPs89CAhb24_cnEABOKyLqIGlMxDptYY',
    appId: '1:892944225380:ios:85b9f6a31c607e3ab53b71',
    messagingSenderId: '892944225380',
    projectId: 'bitirmeprojesi-bd29f',
    storageBucket: 'bitirmeprojesi-bd29f.appspot.com',
    iosBundleId: 'com.example.bitirmeProjesi.RunnerTests',
  );
}
